version: '3.1'
services:

 lb:
  image: dockercloud/haproxy
  ports:
  - 80:80
  - 443:443
  links:
  - web
  networks:
  - nw
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock

 web:
  restart: always
  build: .
  ports:
  - 80
  - 443
  volumes:
  - ./website:/var/www/html/
  depends_on:
  - db
  networks:
  - nw
  links:
  - db

 db:
  image: mariadb:latest
  restart: always
  volumes:
  - ./mysql:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
   MYSQL_DATABASE: ${MYSQL_DATABASE}
   MYSQL_USER: ${MYSQL_USER}
   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  networks:
  - nw

 redis:
  image: redis
  restart: always
  networks:
  - nw
  ports:
  - 6379:6379

 dbadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  ports:
  - 8080:80
  networks:
  - nw

networks:
 nw:
  driver: bridge






